1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [3]:
print(np.version.version)
print(np.get_printoptions())

1.22.4
{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


3. Create a null vector of size 10

In [4]:
v = np.zeros(10)

6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
v = (np.arange(10) == 4) * 1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [6]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
v = np.arange(10)
v = v[::-1]
v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
v = np.arange(9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
v = np.nonzero([1,2,0,0,4,0])
v

(array([0, 1, 4], dtype=int32),)

11. Create a 3x3 identity matrix (★☆☆)

In [11]:
v = np.eye(3)
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
v = np.random.uniform((3,3,3))
v

array([1.94641458, 1.07768351, 2.77235468])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
V = np.random.random((10,10))
V.min(), V.max()

(0.00500985299917478, 0.9855307931562947)

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
V = np.random.random(10)
V.mean()

0.509029419536229

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
V = np.ones((10,10))
V[1:-1,1:-1] = 0
V

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

17. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [23]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
V = np.zeros ((8,8))
V[1::2, ::2]= 1
V[::2, 1::2] = 1
V

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
V = (np.random.random(30)*5)+3
V

array([6.27328061, 7.05381886, 6.86817748, 3.99551108, 4.1475677 ,
       5.79405114, 4.19233288, 3.11174741, 4.05425201, 7.24789809,
       7.82865585, 4.31233603, 4.91791601, 3.988217  , 4.82660044,
       3.81166453, 4.71390445, 7.9573683 , 4.22792707, 7.67628174,
       6.71081216, 3.69493555, 6.6136063 , 7.94631044, 7.3415439 ,
       7.79831378, 7.34732115, 7.77524028, 7.5492662 , 5.51931677])

28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


30. How to find common values between two arrays? (★☆☆)

In [31]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = np.array([1, 3, 4])
print(np.intersect1d(ar1, ar2))

[1 3 4]


40. Create a random vector of size 10 and sort it (★★☆)

In [34]:
np.sort(np.random.random(10))

array([0.23547415, 0.24224217, 0.41766862, 0.50694014, 0.55908873,
       0.61674699, 0.64088045, 0.67721848, 0.6831058 , 0.68440673])

42. Consider two random array A and B, check if they are equal (★★☆)

In [36]:
ar1 = np.random.random(10)
ar2 = np.random.random(10)
np.allclose(ar1, ar2)

False

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [39]:
v = np.random.random((10,2))
x,y = v[:,0], v[:,1]
x1 = np.sqrt(x**2+y**2)
y1 = np.arctan2(y,x)
print(x1)
print(y1)

[0.91720383 1.02187907 1.06244813 0.43108492 0.48820292 0.92960839
 1.19593403 0.79608917 1.10795794 0.96985158]
[1.42034335 1.31961463 0.72970081 0.89664525 1.32600076 0.95890351
 0.81866583 0.8234031  1.07519185 0.74449442]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [45]:
v = np.arange(10, dtype = np.float32)
print(v)
v = v.astype(np.int32)
v

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

58. Subtract the mean of each row of a matrix (★★☆)

In [46]:
v = np.random.rand(5, 10)
v
v1 = v - v.mean(axis = 1, keepdims = True)
print(v1)

[[-0.31101665  0.52313037 -0.35105775  0.17541514 -0.00557997 -0.11172632
  -0.34525188  0.38668304  0.02049484  0.01890917]
 [-0.02929093  0.29558366  0.26699972  0.17922841 -0.34129914 -0.41247165
  -0.33500678  0.50164183  0.14435455 -0.26973968]
 [-0.04233175 -0.20976449  0.44355685  0.30151639 -0.22823572 -0.15814729
   0.49309797 -0.41255267 -0.43338045  0.24624115]
 [ 0.38738447 -0.26542549  0.13624575 -0.2559051   0.33781533  0.31418909
  -0.31458572 -0.07939026  0.05391369 -0.31424177]
 [-0.20761361 -0.24983223 -0.04608249 -0.07210346  0.47037067 -0.28395251
   0.61377874 -0.09040804  0.07062139 -0.20477844]]
